apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: launchpad-stage

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - migration-job.yaml
  - keycloak-schema-job.yaml
  - backend.yaml
  - keycloak.yaml
  - network-policy.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: partner-ai-launchpad
      launchpad.redhat.com/environment: stage
    includeSelectors: true
