apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: partner-ai-launchpad

resources:
  - ../../base
  - flightpath-clusters.yaml
  - argocd-trustyai-rbac.yaml

images:
  - name: backend
    newName: quay.io/redhat-gpte/launchpad-backend
    digest: sha256:1e097350a1cb07eea5a991fa40d4fe8afe44cc48923f8a223a3eef07adeb8dcb
  - name: partner-portal
    newName: quay.io/redhat-gpte/launchpad-portal
    digest: sha256:f97cd9cd7a3d51eb5709c92131c11ae02e73901b5232ad7731171f286d6b10c3
  - name: admin
    newName: quay.io/redhat-gpte/launchpad-admin
    digest: sha256:d76bf69b7720efced8ed328e0a0ac863d2e6f96b056f67bb3e6507a73a37ee4e
  - name: postgres
    newName: docker.io/library/postgres
    digest: sha256:075f7ba66bc9b3ce7d6b8b635208ff61cd7cf1a67d71ec530eec5d7ae0cbe571
  - name: registry.redhat.io/openshift4/ose-oauth-proxy
    newName: registry.redhat.io/openshift4/ose-oauth-proxy
    digest: sha256:e68637bc28cd2e0820d75650ed3019b64247d9b2760e455bf6c1af7d5d66b7af
  - name: quay.io/oauth2-proxy/oauth2-proxy
    newName: quay.io/oauth2-proxy/oauth2-proxy
    digest: sha256:786bed0f000c0f8a7b31619244ebab02406a8856a4faf3f5fb1df61fbd6c30ed

patches:
  - path: patch-configmap.yaml
  - path: patch-postgres-pvc.yaml
  - path: patch-generated-secrets.yaml
  - path: patch-local-provisioner-rbac.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: launchpad-registry-pull
  - target:
      group: batch
      version: v1
      kind: CronJob
    patch: |-
      - op: replace
        path: /spec/suspend
        value: true
      - op: add
        path: /spec/jobTemplate/spec/template/spec/imagePullSecrets
        value:
          - name: launchpad-registry-pull
