apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: launchpad-flightpath-candidate

resources:
  - ../../base
  - ../../../../catalog
  - candidate-clusters.yaml
  - candidate-rbac.yaml
  - candidate-maas.yaml
  - public-access-ha.yaml
  - participant-identity-reconciler.yaml

configMapGenerator:
  - name: flightpath-candidate-serve-llms-catalog
    files:
      - catalog-item.yaml=intel-llm-cpu-serving.catalog-item.yaml
  - name: flightpath-candidate-agent-201-catalog
    files:
      - catalog-item.yaml=intel-xeon6-agent-201.catalog-item.yaml
  - name: flightpath-candidate-multi-agent-catalog
    files:
      - catalog-item.yaml=multi-agent-quickstart.catalog-item.yaml
  - name: flightpath-candidate-hybrid-fraud-catalog
    files:
      - catalog-item.yaml=hybrid-fraud-detection.catalog-item.yaml
  - name: flightpath-candidate-network-operations-catalog
    files:
      - catalog-item.yaml=network-operations-agent.catalog-item.yaml
  - name: flightpath-candidate-agent-reliability-catalog
    files:
      - catalog-item.yaml=agent-reliability.catalog-item.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: backend
    newName: ghcr.io/rhpds/launchpad-backend
    digest: sha256:46eeb5f881369e843c03fe9e4c0a252798914332b1b3d429605f4beccdc3b053
  - name: partner-portal
    newName: ghcr.io/jkershawrh/launchpad-portal
    digest: sha256:ec41032da5dcd38680ce59e077bb67619f7170d68691f0c9376051505404a2a3
  - name: admin
    newName: ghcr.io/jkershawrh/launchpad-admin
    digest: sha256:4607beb42f2d5b677dee5d7c0f1772b70319406feb947b7ca241644ff50e697e
  - name: postgres
    newName: docker.io/library/postgres
    digest: sha256:075f7ba66bc9b3ce7d6b8b635208ff61cd7cf1a67d71ec530eec5d7ae0cbe571
  - name: registry.redhat.io/openshift4/ose-oauth-proxy
    newName: registry.redhat.io/openshift4/ose-oauth-proxy
    digest: sha256:e68637bc28cd2e0820d75650ed3019b64247d9b2760e455bf6c1af7d5d66b7af
  - name: quay.io/oauth2-proxy/oauth2-proxy
    newName: quay.io/oauth2-proxy/oauth2-proxy
    digest: sha256:786bed0f000c0f8a7b31619244ebab02406a8856a4faf3f5fb1df61fbd6c30ed

patches:
  - path: patch-configmap.yaml
  - path: patch-routes.yaml
  - path: patch-postgres-pvc.yaml
  - path: patch-generated-secrets.yaml
  - path: patch-remove-shared-rbac.yaml
  - path: patch-runtime.yaml
  - path: patch-sales-entry-routes.yaml
  - path: patch-sales-entry-selectors.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: partner-ai-launchpad
      launchpad.redhat.com/environment: flightpath-candidate
    includeSelectors: false
