import { useCallback, useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../api/client';
import type { AdminObservability, LifecycleHealth, ProvisioningObservation, SeatObservation } from '../api/types';

type View = 'labs' | 'models' | 'clusters' | 'events';
type Tone = 'green' | 'yellow' | 'red' | 'gray';
const tone: Record<Tone, string> = { green: 'border-[#3E8635]/70 bg-[#17351f] text-[#9AD98D]', yellow: 'border-[#F0AB00]/70 bg-[#3a2d0b] text-[#F4C145]', red: 'border-[#C9190B]/80 bg-[#3b1717] text-[#FF8A80]', gray: 'border-[#555]/70 bg-[#242424] text-[#B8BBBE]' };
const dot: Record<Tone, string> = { green: 'bg-[#73BC63]', yellow: 'bg-[#F4C145]', red: 'bg-[#FA6868]', gray: 'bg-[#8A8D90]' };
const finalStates = ['completed', 'completed_with_errors', 'failed', 'reclaimed'];

function seatTone(seat: SeatObservation, errors: number, limited: number, p95: number): Tone {
  const usage = seat.resource_usage;
  if (['failed', 'validation_failed', 'cleanup_failed'].includes(seat.status) || errors || (usage?.available && (usage.pod_count || 0) > 0 && usage.ready_pods === 0)) return 'red';
  if (['requested', 'pending', 'queued', 'provisioning', 'validating', 'resetting', 'reclaiming'].includes(seat.status) || limited || p95 >= 60_000 || (usage?.restarts || 0) > 0 || (usage?.available && (usage.ready_pods || 0) < (usage.pod_count || 0))) return 'yellow';
  return ['ready', 'active'].includes(seat.status) ? 'green' : 'gray';
}

function Badge({ value }: { value: Tone }) { const label = { green: 'Healthy', yellow: 'Watch', red: 'Critical', gray: 'No signal' }[value]; return <span className={`inline-flex items-center gap-1 rounded-full border px-2 py-1 text-[10px] font-bold uppercase ${tone[value]}`}><i className={`h-2 w-2 rounded-full ${dot[value]}`} />{label}</span>; }
function Legend() { return <div className="flex flex-wrap gap-3 text-xs text-[#8A8D90]">{(['green', 'yellow', 'red', 'gray'] as Tone[]).map((item) => <span key={item} className="flex items-center gap-1"><i className={`h-2.5 w-2.5 rounded-sm ${dot[item]}`} />{{ green: 'Healthy', yellow: 'Watch', red: 'Critical', gray: 'No signal' }[item]}</span>)}</div>; }
function Tab({ active, children, onClick }: { active: boolean; children: string; onClick: () => void }) { return <button role="tab" aria-selected={active} onClick={onClick} className={`shrink-0 border-b-2 px-5 py-3 text-sm font-semibold ${active ? 'border-[#EE0000] text-white' : 'border-transparent text-[#8A8D90] hover:text-white'}`}>{children}</button>; }
function Metric({ label, value, detail, alert }: { label: string; value: string | number; detail: string; alert?: boolean }) { return <div className="rounded-lg border border-[#333] bg-[#212121] p-4"><p className="text-[11px] font-bold uppercase tracking-wider text-[#8A8D90]">{label}</p><p className={`mt-1 text-2xl font-bold ${alert ? 'text-[#FA6868]' : 'text-white'}`}>{value}</p><p className="text-xs text-[#8A8D90]">{detail}</p></div>; }

function SeatGrid({ data, lab }: { data: AdminObservability; lab: ProvisioningObservation }) {
  return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">{lab.seats.map((seat) => { const rows = data.llm.attribution.filter((row) => row.session_id === seat.session_id); const requests = rows.reduce((n, row) => n + row.requests, 0); const errors = rows.reduce((n, row) => n + row.errors, 0); const limited = rows.reduce((n, row) => n + row.rate_limited, 0); const tokens = rows.reduce((n, row) => n + row.total_tokens, 0); const p95 = Math.max(0, ...rows.map((row) => row.p95_latency_ms || 0)); const health = seatTone(seat, errors, limited, p95); return <article key={`${lab.order_id}-${seat.seat_number}`} className={`flex min-h-[270px] flex-col rounded-lg border p-4 ${tone[health]}`}><div className="flex items-start justify-between gap-2"><div><h3 className="text-lg font-bold text-white">Seat {String(seat.seat_number).padStart(2, '0')}</h3><p className="text-xs opacity-80">{seat.status.replaceAll('_', ' ')}</p></div><Badge value={health} /></div><p className="mt-3 truncate font-mono text-[10px] text-[#D2D2D2]" title={seat.namespace || undefined}>{seat.namespace || 'namespace pending'}</p><div className="mt-3 grid grid-cols-2 gap-2 border-y border-white/10 py-3 text-xs"><div><span className="opacity-65">AI requests</span><p className="font-mono text-white">{requests}</p></div><div><span className="opacity-65">P95</span><p className="font-mono text-white">{p95 ? `${Math.round(p95 / 1000)}s` : '—'}</p></div><div><span className="opacity-65">Errors</span><p className="font-mono text-white">{errors}</p></div><div><span className="opacity-65">Tokens</span><p className="font-mono text-white">{tokens.toLocaleString()}</p></div></div><div className="mt-3 grid grid-cols-2 gap-2 text-[11px]"><div><span className="opacity-65">CPU</span><p className="font-mono text-white">{seat.resource_usage?.available ? `${seat.resource_usage.cpu_millicores || 0}m` : '—'}</p></div><div><span className="opacity-65">Memory</span><p className="font-mono text-white">{seat.resource_usage?.available ? `${seat.resource_usage.memory_mib || 0} MiB` : '—'}</p></div><div><span className="opacity-65">Pods</span><p className="font-mono text-white">{seat.resource_usage?.available ? `${seat.resource_usage.ready_pods || 0}/${seat.resource_usage.pod_count || 0}` : '—'}</p></div><div><span className="opacity-65">Restarts</span><p className="font-mono text-white">{seat.resource_usage?.available ? seat.resource_usage.restarts || 0 : '—'}</p></div></div>{seat.detail_url && <Link to={seat.detail_url} className="mt-auto pt-3 text-xs font-semibold text-white underline">Inspect seat</Link>}</article>; })}</div>;
}

function Labs({ data, selected, setSelected }: { data: AdminObservability; selected: string; setSelected: (id: string) => void }) { const active = data.provisioning.filter((lab) => !finalStates.includes(lab.status)); const labs = active.length ? active : data.provisioning; const lab = labs.find((item) => item.order_id === selected) || labs[0]; if (!lab) return <Empty text="No labs are available." />; return <div className="space-y-5"><div className="rounded-lg border border-[#333] bg-[#212121] p-5"><label htmlFor="lab-select" className="mb-2 block text-xs font-bold uppercase text-[#8A8D90]">Select a lab</label><select id="lab-select" value={lab.order_id} onChange={(event) => setSelected(event.target.value)} className="w-full max-w-3xl rounded border border-[#555] bg-[#151515] px-3 py-2.5 text-white">{labs.map((item) => <option key={item.order_id} value={item.order_id}>{item.name} · {item.ready_seats}/{item.seats_requested} ready · {item.cluster_ref || 'unassigned'}</option>)}</select><div className="mt-3 flex flex-wrap gap-4 text-xs text-[#8A8D90]"><span>{lab.catalog_item_id}</span><span>{lab.ready_seats}/{lab.seats_requested} ready</span><span className={lab.failed_seats ? 'text-[#FA6868]' : ''}>{lab.failed_seats} failed</span>{lab.detail_url && <Link to={lab.detail_url} className="text-[#73BCF7]">Manage lab</Link>}</div></div><div className="flex flex-col justify-between gap-2 sm:flex-row"><div><h2 className="text-lg font-semibold text-white">Seat health</h2><p className="text-sm text-[#8A8D90]">Live lifecycle, resource, and AI usage per participant.</p></div><Legend /></div><SeatGrid data={data} lab={lab} /></div>; }

function Models({ data }: { data: AdminObservability }) { return <div className="space-y-5"><div className="flex justify-between"><div><h2 className="text-lg font-semibold text-white">AI model pressure</h2><p className="text-sm text-[#8A8D90]">Replica readiness and attributed traffic pressure.</p></div><Legend /></div>{data.llm.models.length === 0 ? <Empty text="No model inventory available." /> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.llm.models.map((model) => { const rows = data.llm.attribution.filter((row) => row.model_id === model.model_id); const errors = rows.reduce((n, row) => n + row.errors, 0); const limited = rows.reduce((n, row) => n + row.rate_limited, 0); const requests = rows.reduce((n, row) => n + row.requests, 0); const p95 = Math.max(0, ...rows.map((row) => row.p95_latency_ms || 0)); const health: Tone = model.ready_replicas === 0 ? 'red' : model.ready_replicas < model.desired_replicas || errors || limited || p95 >= 60_000 ? 'yellow' : 'green'; return <article key={model.model_id} className={`rounded-lg border p-5 ${tone[health]}`}><div className="flex justify-between gap-3"><div><h3 className="font-semibold text-white">{model.display_name}</h3><p className="font-mono text-xs opacity-70">{model.model_id}</p></div><Badge value={health} /></div><div className="my-4 rounded bg-black/15 p-4 text-center"><p className="text-xs opacity-70">READY REPLICAS</p><p className="text-3xl font-bold text-white">{model.ready_replicas} / {model.desired_replicas}</p></div><div className="grid grid-cols-4 text-center text-xs"><div><span className="opacity-65">Requests</span><p>{requests}</p></div><div><span className="opacity-65">P95</span><p>{p95 ? `${Math.round(p95 / 1000)}s` : '—'}</p></div><div><span className="opacity-65">Errors</span><p>{errors}</p></div><div><span className="opacity-65">Limited</span><p>{limited}</p></div></div><div className="mt-4 border-t border-white/10 pt-3 text-xs"><p>{model.hardware || 'Unknown hardware'}</p><p className="truncate opacity-70">{model.backend || 'Unknown backend'}</p><p className="truncate opacity-70">{model.route}</p></div></article>; })}</div>}{data.llm.telemetry_gaps.length > 0 && <div className={`rounded border p-3 text-sm ${tone.yellow}`}>Telemetry gaps: {data.llm.telemetry_gaps.join(' · ')}</div>}</div>; }

function Clusters({ data }: { data: AdminObservability }) { return <div className="space-y-5"><div className="flex justify-between"><div><h2 className="text-lg font-semibold text-white">Cluster performance</h2><p className="text-sm text-[#8A8D90]">Placement eligibility and available headroom.</p></div><Legend /></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.clusters.map((cluster) => { const health: Tone = !cluster.healthy ? 'red' : !cluster.eligible || cluster.available_cpu_millicores < 20_000 || cluster.available_memory_mib < 32_768 || cluster.available_pods < 50 ? 'yellow' : 'green'; return <article key={cluster.cluster_id} className={`rounded-lg border p-5 ${tone[health]}`}><div className="flex justify-between"><div><h3 className="text-lg font-semibold text-white">{cluster.cluster_name || cluster.cluster_id}</h3><p className="font-mono text-xs opacity-70">{cluster.cluster_id}</p></div><Badge value={health} /></div><div className="my-5 grid grid-cols-3 gap-2 text-center"><div><span className="text-xs opacity-65">CPU free</span><p className="font-mono text-lg text-white">{Math.round(cluster.available_cpu_millicores / 1000)} cores</p></div><div><span className="text-xs opacity-65">Memory</span><p className="font-mono text-lg text-white">{Math.round(cluster.available_memory_mib / 1024)} GiB</p></div><div><span className="text-xs opacity-65">Pod slots</span><p className="font-mono text-lg text-white">{cluster.available_pods}</p></div></div><p className="border-t border-white/10 pt-3 text-xs">{cluster.active_workshops} workshops · {cluster.active_seats} seats · {cluster.active_sessions} sessions</p>{cluster.reason && <p className="mt-2 text-xs opacity-70">{cluster.reason}</p>}</article>; })}</div></div>; }

function Events({ data, lifecycle }: { data: AdminObservability; lifecycle: LifecycleHealth | null }) { return <div className="space-y-5"><div><h2 className="text-lg font-semibold text-white">Lifecycle and platform events</h2><p className="text-sm text-[#8A8D90]">Failures, in-flight activity, retries, and telemetry gaps.</p></div><div className="grid gap-5 xl:grid-cols-3"><EventGroup title="Attention queue" empty="No seat alerts.">{data.resolution.map((row) => <div key={`${row.order_id}-${row.seat_number}`} className={`rounded border p-3 text-xs ${row.state === 'attention' ? tone.red : tone.yellow}`}><strong className="text-white">{row.name} · seat {row.seat_number}</strong><p>{row.status.replaceAll('_', ' ')}</p><p className="opacity-70">{row.message}</p></div>)}</EventGroup><EventGroup title="In-flight operations" empty="No seat operations in flight.">{data.inflight.map((row) => <div key={row.order_id} className="rounded border border-[#0071C5]/60 bg-[#102d43] p-3 text-xs text-[#8CCCF5]"><strong className="text-white">{row.name}</strong><p>{row.inflight_seats} seats · oldest {duration(row.oldest_seconds)}</p></div>)}</EventGroup><EventGroup title="Lifecycle workers" empty="No active lifecycle jobs.">{(lifecycle?.jobs || []).map((job) => <div key={job.job_id} className={`rounded border p-3 text-xs ${job.status === 'failed' ? tone.red : tone.gray}`}><strong className="text-white">{job.operation.replaceAll('_', ' ')}</strong><p>{job.cluster_ref || 'unassigned'} · {job.status} · attempt {job.attempts}/{job.max_attempts}</p>{job.last_error && <p className="text-[#FA6868]">{job.last_error}</p>}</div>)}</EventGroup></div></div>; }
function EventGroup({ title, empty, children }: { title: string; empty: string; children: React.ReactNode[] }) { return <section className="rounded-lg border border-[#333] bg-[#212121] p-4"><h3 className="mb-3 font-semibold text-white">{title}</h3><div className="space-y-2">{children.length ? children : <p className="rounded bg-[#181818] p-4 text-sm text-[#8A8D90]">{empty}</p>}</div></section>; }
function duration(seconds?: number | null) { if (seconds == null) return '—'; return seconds < 60 ? `${seconds}s` : `${Math.floor(seconds / 60)}m`; }
function Empty({ text }: { text: string }) { return <p className="rounded-lg border border-[#333] bg-[#212121] p-10 text-center text-[#8A8D90]">{text}</p>; }

export default function Observability() {
  const [data, setData] = useState<AdminObservability | null>(null); const [lifecycle, setLifecycle] = useState<LifecycleHealth | null>(null); const [view, setView] = useState<View>('labs'); const [selected, setSelected] = useState(''); const [error, setError] = useState('');
  const load = useCallback(() => { api.getAdminObservability().then((payload) => { setData(payload); setError(''); setSelected((current) => payload.provisioning.some((lab) => lab.order_id === current) ? current : payload.provisioning.find((lab) => !finalStates.includes(lab.status))?.order_id || payload.provisioning[0]?.order_id || ''); }).catch((reason) => setError(String(reason))); api.getLifecycleHealth().then(setLifecycle).catch(() => setLifecycle(null)); }, []);
  useEffect(() => { load(); const timer = window.setInterval(load, 15_000); return () => window.clearInterval(timer); }, [load]);
  const alerts = useMemo(() => (data?.summary.seats_attention || 0) + (lifecycle?.summary.failed || 0), [data, lifecycle]);
  if (!data) return <div className="mx-auto max-w-7xl p-8 text-[#8A8D90]">{error ? `Observability unavailable: ${error}` : 'Loading observability…'}</div>;
  return <div className="mx-auto max-w-[1600px] space-y-6 px-6 py-8"><div className="flex flex-col justify-between gap-4 md:flex-row"><div><p className="text-xs font-bold uppercase tracking-widest text-[#73BCF7]">Pilot control room</p><h1 className="mt-1 text-3xl font-bold text-white">Lab observability</h1><p className="mt-2 text-sm text-[#8A8D90]">Participant seats, AI serving, cluster capacity, and lifecycle events. Refreshes every 15 seconds.</p></div><div className="flex items-center gap-3"><span className="text-xs text-[#6A6E73]">Updated {new Date(data.generated_at).toLocaleTimeString()}</span><button onClick={load} className="rounded border border-[#555] px-3 py-2 text-xs text-white">Refresh</button>{data.grafana.configured && data.grafana.url && <a href={data.grafana.url} target="_blank" rel="noreferrer" className="rounded bg-[#0071C5] px-3 py-2 text-xs font-semibold text-white">Grafana ↗</a>}</div></div><div className="grid grid-cols-2 gap-3 lg:grid-cols-6"><Metric label="Clusters" value={`${data.summary.clusters_healthy}/${data.summary.clusters_total}`} detail="healthy" /><Metric label="Active labs" value={data.summary.labs_active} detail="orders" /><Metric label="Ready seats" value={data.summary.seats_active} detail="environments" /><Metric label="In flight" value={data.summary.seats_inflight} detail="seat operations" /><Metric label="Alerts" value={alerts} detail="requires review" alert={alerts > 0} /><Metric label="AI requests" value={data.llm.summary.requests_observed} detail={`${data.llm.summary.attributed_requests} attributed`} /></div><section className="overflow-hidden rounded-lg border border-[#333] bg-[#181818]"><div role="tablist" className="flex overflow-x-auto border-b border-[#333]"><Tab active={view === 'labs'} onClick={() => setView('labs')}>Labs & seats</Tab><Tab active={view === 'models'} onClick={() => setView('models')}>AI models</Tab><Tab active={view === 'clusters'} onClick={() => setView('clusters')}>Clusters</Tab><Tab active={view === 'events'} onClick={() => setView('events')}>Events & alerts</Tab></div><div className="p-5 lg:p-6">{view === 'labs' && <Labs data={data} selected={selected} setSelected={setSelected} />}{view === 'models' && <Models data={data} />}{view === 'clusters' && <Clusters data={data} />}{view === 'events' && <Events data={data} lifecycle={lifecycle} />}</div></section></div>;
}
