apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../arena

patches:
  - path: patch-ha-config.yaml
  - path: patch-ha-backend-reload.yaml
  - path: patch-ha-workers.yaml
  - path: patch-ha-scheduler.yaml
  - path: patch-disable-legacy-reconciler.yaml
