apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: partner-ai-launchpad

resources:
  - ../../base
  - buildconfig.yaml

patches:
  - path: patch-routes.yaml
  - path: patch-configmap.yaml
  - path: patch-remove-frontend.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: backend
    path: patch-backend-no-oauth.yaml

images:
  - name: backend
    newName: image-registry.openshift-image-registry.svc:5000/partner-ai-launchpad/launchpad-backend
    newTag: latest
