apiVersion: apps/v1
kind: Deployment
metadata:
  name: partner-portal
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  replicas: 1
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: launchpad
spec:
  host: launchpad.apps.oberon.fm2aihpcsed.com
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: launchpad-admin
spec:
  host: launchpad-admin.apps.oberon.fm2aihpcsed.com
