apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: partner-ai-launchpad

resources:
  - ../../base
  - ../../observability
  - buildconfig.yaml
  - operations-automation.yaml
  - reliability.yaml
  - argocd-monitoring-rbac.yaml
  - arena-clusters.yaml

patches:
  - path: patch-routes.yaml
  - path: patch-configmap.yaml
  - path: patch-postgres-pvc.yaml
  - path: patch-runtime.yaml
  - path: patch-generated-secrets.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: backend
    path: patch-backend-no-oauth.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: NetworkPolicy
      name: public-access-gateway-ingress
    patch: |-
      - op: replace
        path: /spec/ingress/0/from/1/podSelector/matchLabels
        value:
          app.kubernetes.io/name: cloudflare-tunnel

images:
  - name: backend
    newName: image-registry.openshift-image-registry.svc:5000/partner-ai-launchpad/launchpad-backend
    digest: sha256:f294eb6bc1d60a72b2f058956ae166478346dae894fb653b142ea81fdfa5d4be
  - name: partner-portal
    newName: image-registry.openshift-image-registry.svc:5000/partner-ai-launchpad/launchpad-portal
    digest: sha256:f97cd9cd7a3d51eb5709c92131c11ae02e73901b5232ad7731171f286d6b10c3
  - name: admin
    newName: image-registry.openshift-image-registry.svc:5000/partner-ai-launchpad/launchpad-admin
    digest: sha256:d76bf69b7720efced8ed328e0a0ac863d2e6f96b056f67bb3e6507a73a37ee4e
