apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: partner-ai-launchpad

resources:
  - ../../base
  - ../../observability
  - buildconfig.yaml
  - operations-automation.yaml
  - reliability.yaml
  - argocd-monitoring-rbac.yaml
  - arena-clusters.yaml

patches:
  - path: patch-routes.yaml
  - path: patch-configmap.yaml
  - path: patch-postgres-pvc.yaml
  - path: patch-runtime.yaml
  - path: patch-generated-secrets.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: backend
    path: patch-backend-no-oauth.yaml

images:
  - name: backend
    newName: image-registry.openshift-image-registry.svc:5000/partner-ai-launchpad/launchpad-backend
    digest: sha256:ebdde2a70d8a98f6ead036f7baf2f96c1bf2abc989f99ee81084d09b9fdb7d9c
  - name: partner-portal
    newName: image-registry.openshift-image-registry.svc:5000/partner-ai-launchpad/launchpad-portal
    digest: sha256:43e8dafd8276faf598c3ad3bf7090bb48129ced6cb131a7e9925f6c4aca9aaa7
  - name: admin
    newName: image-registry.openshift-image-registry.svc:5000/partner-ai-launchpad/launchpad-admin
    digest: sha256:80f0bdb3ba2d0c0c0d98dab9906f1018bfe9c1284e458e314f5f4dc667fb92eb
